const data = {

    products: [
      {
        name: 'Wine 2640',
        slug: 'Vino-500-ml',
        category: 'Red Wine',
        image: '/imaages/p1.jpg',
        price: 120,
        countInStock: 10,
        brand: 'chapeuwine',
        rating: 4.3,
        numReviews: 10,
        description: 'high quality Wine',
      },
      {
        name: 'Wine ilurce',
        slug: 'Vino-500-mls',
        category: 'Rose Wine',
        image: '/images/p2.jpg',
        price: 101,
        countInStock: 10,
        brand: 'chapeuwine',
        rating: 4.4,
        numReviews: 10,
        description: 'high quality Wine',
      },
      {
        name: 'Wine Petit',
        slug: 'Vino-200-ml',
        category: 'Red Wine',
        image: '/images/p3.jpg',
        price: 120,
        countInStock: 10,
        brand: 'chapeuwine',
        rating: 4.3,
        numReviews: 10,
        description: 'high quality Wine',
      },
      {
        name: 'Wine mondeu',
        slug: 'Vino-100-ml',
        category: 'Red Wine',
        image: '/images/p4.jpg',
        price: 120,
        countInStock: 10,
        brand: 'chapeuwine',
        rating: 4.3,
        numReviews: 10,
        description: 'high quality Wine',
      },
    ],
};

export default data;
